.\" Manpage for mintcast.
.\" Contact limbov8@gmail.com to correct errors or typos.
.TH man 1 "31 May 2018" "0.1" "MINTCAST man page"
.SH NAME
mintcast \- generate vector, raster mbtiles and configure json files for GeoTiff, NetCDF and already-tiled map resources.

.SH SYNOPSIS
mintcast -qml --include-config ...

.SH DESCRIPTION
mintcast will generate vector, raster mbtiles and configure json files for GeoTiff, NetCDF and already-tiled map resources. Also, it will update the website settings and database. 

.SH OPTIONS
.IP -qml
mintcast will generate vector, raster mbtiles and configure json files for GeoTiff, NetCDF and already-tiled map resources. Also, it will update the website settings and database. mintcast will generate vector, raster mbtiles and configure json files for GeoTiff, NetCDF and already-tiled map resources. Also, it will update the website settings and database. 
.TP
.BI -f " filename"
Specifies the file you want to edit. This option must be given with the
.BR " -e " "or the " "-d " option.

.SH SEE ALSO
tippecanoe(1)

.SH AUTHOR
Libo Liu (limbov8@gmail.com), Adam Vaccaro (avaccaro@usc.edu), Shiwei Huang (shiweihu@usc.edu)