#!/usr/bin/env sh
helper_parameter(){
    POSITIONAL=()
    while [[ $# -gt 0 ]]
    do
    key="$1"
    case $key in
        -t|--type)
        DATASET_TYPE="$2"
        shift 
        shift 
        ;;
        -q|--qml)
        QML_FILE="$2"
        shift # past argument
        shift # past value
        ;;
        -d|--dir)
        DATASET_DIR="$2"
        shift 
        shift 
        ;;
        -h|--ssh-user)
        SSH_USER="$2"
        shift 
        shift 
        ;;
        -m|--md5vector)
        VECTOR_MD5="$2"
        shift
        shift
        ;;
        -u|--structure)
        DATASET_DIR_STRUCTURE="$2"
        shift 
        shift 
        ;;
        -z|--output-dir-structure)
        OUTPUT_DIR_STRUCTURE_FOR_TIMESERIES="$2"
        shift
        shift
        ;;
        -s|--start-time)
        START_TIME="$2"
        shift 
        shift 
        ;;
        -e|--end-time)
        END_TIME="$2"
        shift 
        shift 
        ;;
        --datatime-format)
        DATATIME_FORMAT="$2"
        shift
        shift
        ;;
        --single-subdataset)
        NETCDF_SINGLE_SUBDATASET="$2"
        shift
        shift
        ;;
        --load-colormap)
        COLORMAP_USE_LOADED="YES"
        COLOR_TABLE="$2"
        shift
        shift
        ;;
        -l|--layer-name)
        LAYER_NAME="$2"
        shift
        shift
        ;;
        -o|--output)
        DATASET_NAME="$2"
        shift
        shift
        ;;
        -b|--bounds)
        CLIP_BOUNDS="$2"
        shift
        shift
        ;;
        --first-file)
        FIRST_FILE=YES
        shift
        ;;
        --time-stamp)
        TIME_STAMP="$2"
        shift
        shift
        ;;
        --time-steps)
        TIME_STEPS="$2"
        shift
        shift
        ;;
        --chart-type)
        CHART_TYPE="$2"
        shift
        shift
        ;;
        --time-format)
        TIME_FORMAT="$2"
        shift
        shift
        ;;
        --target-json-path)
        TARGET_JSON_PATH="$2"
        shift
        shift
        ;;
        --server)
        TILESEVER_PROG="$2"
        shift
        shift
        ;;
        --port)
        TILESEVER_PORT="$2"
        shift
        shift
        ;;
        --bind)
        TILESEVER_BIND="$2"
        shift
        shift
        ;;
        --with-shape-file)
        USE_SS_SHAPE="YES"
        SS_BOUNDARY="$2"
        shift
        shift
        ;;
        --dev-mode-off)
        DEV_MODE=NO
        shift
        ;;
        --tile-server-root)
        TILESERVER_ROOT="$2"
        shift
        shift
        ;;
        --force-restart-tileserver)
        RESTART_TILESERVER="YES"
        shift
        ;;
        --target-mbtiles-path)
        TARGET_MBTILES_PATH="$2"
        shift
        shift
        ;;
        --scp-to-default-server)
        SCP_TO_SERVER="$SCP_TO_SERVER_DEFAULT"
        shift
        ;;
        --scp-to-server)
        SCP_TO_SERVER="$2"
        shift
        shift
        ;;
        --without-website)
        NO_WEBSITE_UPDATE=YES
        shift 
        ;;
        --tiled-ext)
        TILED_FILE_EXT="$2"
        shift
        shift
        ;;
        --with-quality-assessment)
        WITH_QUALITIY_ASSESSMENT="YES"
        shift
        ;;
        --disable-clip)
        DISABLE_CLIP="YES"
        shift
        ;;
        --disable-new-res)
        GENERATE_NEW_RES="NO"
        shift
        ;;
        --verbose)
        VERBOSE="YES"
        shift
        ;;
        --disable-raster-tile)
        GENERATE_RASTER_TILE="NO"
        shift
        ;;
        --disable-vector-tile)
        GENERATE_VECTOR_TILE="NO"
        shift
        ;;
        --force-proj-first)
        FORCE_PROJECTION_FIRST="YES"
        shift
        ;;
        --with-south-sudan-shp)
        USE_SS_SHAPE="YES"
        shift
        ;;
        --add-ssh-key)
        NEW_SSH_KEY="YES"
        shift
        ;;
        -v|--version)
        echo "$VERSION"
        exit 0
        ;;
        -h|--help)
        echo "$USAGE"
        exit 0
        ;;
        *)    # unknown option
        POSITIONAL+=("$1") # save it in an array for later
        shift 
        ;;
    esac
    done

    set -- "${POSITIONAL[@]}" # restore positional parameters
    DATAFILE_PATH="$1"
    # -- for no more flags, [@] reset all parameters
}
